# Generated by Django 4.0.4 on 2022-05-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursechoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ICS', 'Introduction to Computer Systems'), ('IDS', 'Introduction to Data Science'), ('CSPP', 'Computer Science Principles and Programming')], max_length=25, unique=True)),
            ],
        ),
    ]
